### PR TITLE
Add debian pacakging files

### PR DESCRIPTION
**Pull request by IMbackK**
This adds a debian directory to openlara. This allows native .deb binary packages be built for deb based operating systems (debian, devuan, linux mint, ubuntu, maemo-leste, etc) using dpkg-buildpackage, as is required to have ol in the repositories of these oses.

thir pr requires https://github.com/XProger/OpenLara/pull/403

If you want to maintain this in the master branch is a matter of taste. It is also entirely common practice to have this in a seperate branch (maybe called debian or deb) and rebase that branch on master occasionally (for releases).

### CODE REVIEW

**Comment by XProger** [comment]
can you put it into src/platform/nix?

**Comment by IMbackK** [comment]
this needs to be in the root of the git repo for debian ci to be able to build a pacakge from this.

it also builds the sdl2 version not the x11  src/platform/nix, which im really sure why this is sill around since sdl2 covers the same platform, but without the hard x11 dependency

**Comment by XProger** [comment]
sorry, sdl2 is the dependency, one of the project goals - no additional libraries at all, so sdl2 will never be a release platform.

**Comment by IMbackK** [comment]
Thats a pretty strange policy considering that src/platform/nix depends on xlib, a external lib which is a lot worse of a dependency than sdl. (hint: if you dont want this dependency you have to talk the x11 wire protocol yourself)

**Pull request closed without merging**
