### PR TITLE
Fix compilation with SDL2 + GLES2

### PR DESCRIPTION
**Pull request by DanTheMan827**

### CODE REVIEW

**Comment by DanTheMan827** [comment]
@vanfanel does this look right?

**Comment by vanfanel** [comment]
@DanTheMan827 Yes I did.
But I don't get it, sorry. Latest OpenLara builds fine here on SDL2+GLES2.
Can you explain the changes, please? I don't have the code on my head right now :)

**Comment by vanfanel** [comment]
@DanTheMan827 I just built OpenLara against SDL2+GLES2 with your changes and it works fine (whatever they do exactly), in case that helps.

**Comment by DanTheMan827** [comment]
@vanfanel The problem I was getting when trying to build SDL2 with GLES2 is that glGetStringi wasn't declared even though I only selected GLES2
```
arm-buildroot-linux-gnueabihf-g++ -DSDL2_GLES -D_GAPI_GLES2 -std="c++11" `sdl2-config --cflags` -fno-exceptions -fno-rtti -ffunction-sections -fdata-sections -Wl,--gc-sections -DNDEBUG -D__SDL2__ platform/sdl2/main.cpp libs/stb_vorbis/stb_vorbis.c libs/minimp3/minimp3.cpp libs/tinf/tinflate.c -I./ -o OpenLara `sdl2-config --libs` -lGLESv2 -lEGL -lm -lrt -lpthread -lasound -ludev```

**Comment by vanfanel** [comment]
@DanTheMan827 I understand.
Well, it doesn't seem to break anything and you are right, glGetStringi() is GLES3 so it shouldn't be used if built for GLES2.
I didn't notice it because I am using the better opensource graphics stack (I guess you are using the propietary Broadcom stuff?) and glGetStringi() is not a problem here even with GLES2.

**Comment by vanfanel** [comment]
@DanTheMan827 The problem that made you work on this PR has bitten me today, so I did a similar PR for this:
https://github.com/XProger/OpenLara/pull/352

Should you find any problems, please tell @XProger  or me.
I think this can be closed now.

**Pull request closed without merging**
