### PR TITLE
Fix: Increase shotgun damage

### LINKED ISSUE #267: Incorrect shotgun damage
The shotgun does way too little damage. Especially for close range it should be quite deadly for enemies.
[rVLHNPEFqi.zip](https://github.com/XProger/OpenLara/files/4795384/rVLHNPEFqi.zip)
As it is set right now, it's sadly almost useless.

### PR DESCRIPTION
**Pull request by SirTangent**
Closes #267

### CODE REVIEW

**Comment by SirTangent** [comment]
Tested on Raptor, Lion, and Gorilla. Kills in two shots.

**Comment by Richard-L** [comment]
Thank you so much @SirTangent !

In theory, at _very_ close range, a gorilla or lion should die at even 1 shot, as the original game does it, I believe. Maybe would you also have tested this?

**Comment by SirTangent** [comment]
@Richard-L In most cases, I was able to kill a Gorilla with one shot at a very close range. The fix is a temporary solution, as the weapon trace code is the real culprit of the shotgun issue.

But yeah, glad I could help. I love this project, as TR1 is the definition of my childhood. I hope to continue working on it more.

**Comment by Richard-L** [comment]
Would be amazing... XProger has had other priorities :smiley:

**Pull request merged**
