### PR TITLE
Snap Rotation

### PR DESCRIPTION
**Pull request by mrhatkat**
Trying to add snap rotation to the VR controls. Managed to get it so that the HMD camera will be directly affected by Lara's head animation, but now the head tracking is no longer 1:1 with Lara's model. Any ideas on what might be the cause of this?

### CODE REVIEW

**Comment by mrhatkat** [comment]
Still trying to get the snap rotation to work, I've manged to isolate it into two parts, arrow based rotation and head based rotation, but on switching between the two (specifically from arrow to head) the hmd rotation overrides the rotation you are facing in arrow key mode which is disorienting and not the effect I have in mind. I want to have it so that a player can modify the character's and camera's rotation without moving their head ,but still be able to rotate their character and camera using head rotation (snap rotation). @XProger  any ideas on where to look in the code or insights into how the camera/character rotation works?

**Comment by mrhatkat** [comment]
@XProger Where is the code that determines the ratio for real life rotation vs camera rotation( right now if I turn 90 degrees in real life, the camera turns 180 degrees, which I think is the reason why the rotation of Lara does not match the rotation of my body)

**Comment by mrhatkat** [comment]
Managed to implement the modes so that they can seamlessly transition into each other. Pressing num1 puts you in "Standard VR Mode", where the view changes with respect to Lara. Pressing num2 puts you in "Immersive VR Mode" where the view changes with respect to the HMD's rotation.
@XProger Let me know if anything needs to be fixed, hopefully my git abilities have improved since last time.

**Comment by XProger** [comment]
not actual

**Pull request closed without merging**
