### PR TITLE
plumbered a kmsdrm rendering context

### PR DESCRIPTION
**Pull request by vanfanel**
Hi there, XProger

I have "plumbered" a kms/drm rendering context, intended for modern X-less GNU/Linux systems. It's a bit redundant because there's a RetroArch port, but it may be useful to have an standalone version of OpenLara working on the modern Linux framebuffer infraestructure.

At the moment, only FMV videos are displayed: it segfaults before it can render the menu, but I have been looking at all EGL functions and it seems fine to me. I *believe* I am using the right EGL context parameters. Could you please try to help me finding what's wrong? I am not an OpenGL expert, and I don't know the engine innards either, so maybe you can lend a hand.

### CODE REVIEW

**Comment by XProger** [comment]
Nice! I suppose, the problem in FMV data, please check with this data http://xproger.info/projects/OpenLara/files/OpenLara_TR1.7z

**Comment by vanfanel** [comment]
@XProger: The FMV videos are working. What is not working with this kmsdrm platform is the menu and levels. That's why I need your help to determine the problem: context itself is initialized but I can't find the problem with OpenLara OpenGL_ES graphins on top of it.

**Comment by XProger** [comment]
Ok, it's possible to test drm on the x64 Ubuntu desktop? I'm getting -EACCES error on drmModeSetCrtc call. If I ignore this error, then getting SIGSEGV on drmFBGetFromBO because gbm_surface_lock_front_buffer returns NULL.  Probably it's just VirtualBox problem... I need to test it on real linux machine :)

**Comment by vanfanel** [comment]
Yes, Ubuntu x64 works. But you need to be in a real tty (ctrl alt f2 for
example). Real machine probably too.

El sábado, 20 de octubre de 2018, Timur Gagiev <notifications@github.com>
escribió:
> Ok, it's possible to test drm on the x64 Ubuntu desktop? I'm getting
-EACCES error on drmModeSetCrtc call. If I ignore this error, then getting
SIGSEGV on drmFBGetFromBO because gbm_surface_lock_front_buffer returns
NULL. Probably it's just VirtualBox problem... I need to test it on real
linux machine :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/Mcwl4IyzOfK1OjyKWtdAGH32uMoXnzdBUaDQ4kFER6jU1BSBaZbXg8590nRlRsVnPfKeUAqH83-VwG1V8h0w4LJ_XoO-igs0912p0KNEf3tp2q6LK_B07LBaikYqLckDR7qHHBv2fxrmBP2d4TKq6gSk9JJCHQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAzH0fxA58wzej9KkSKRRo1czERd6dLsks5umoq5gaJpZM4XxXPb.gif>

**Comment by XProger** [comment]
After two days of fucking I can say - FUCK THIS SHIT I'M OUT! Latest distros of Ubuntu doesn't able to use Cltr + Alt + Fn combinations, grub config must be fixed... but it works with problem described below. Some other distros have various errors while installing (I tried Debian, Linux Mint). Only Solus was installed with normal Ctrl + Alt + Fn behavior. BUT! life would be too easy if it wasn't FUCKING linux. So I can't switch from virtual console to desktop or another console while drm app is running, even when it crached I also can't do anything because drm context not destroyed properly. Also I can't create half-screen framebuffer (I use this trick for Raspberry Pi). So... I don't know how to debug this on one machine. Any ideas? :)

**Comment by vanfanel** [comment]
@XProger : The easier way to debug this is:
1 - Have Raspbian use VC4 on the Raspberry Pi, instead of BRCM graphics stack (I can send you a ready-to-use image that has a minimal install with everything ready: GCC, GDB, VIM, etc...)
2- Access to the Pi from the desktop PC using GNU/Linux or Windows or what you use, by using SSH.
3- Run the game on the Pi (Raspbian VC4, which allows KMSDRM+GLES) and debug that way.

What do you say? Can I help you by sending my SD card image for the Pi?

**Comment by XProger** [comment]
Thanks, but remote debugging is still needed for this solution, I thought there is way to debug without it. I'll check it again, when I calm down %)

**Comment by vanfanel** [comment]
@XProger : Did you get it to work in the end? As I said, since remote debugging is needed, using a copy of my Raspberry Pi 3 system would be a good idea. Simply ssh into it for gles debugging.

**Comment by XProger** [comment]
nope

**Comment by vanfanel** [comment]
@XProger : I have been trying to debug this myself on the Raspberry Pi (VC4 MESA driver).
The segfault happens here:

```
Thread 1 "OpenLara" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000005555578ae8 in GAPI::discardTarget (color=true, depth=true) at ../../gapi_gl.h:1085
#2  0x0000005555591d84 in Core::validateRenderState () at ../../core.h:799
#3  0x0000005555592b5c in Core::DIP (mesh=0x555696e168, range=...) at ../../core.h:1002
#4  0x0000005555592ca0 in Mesh::render (this=0x555696e160, range=...) at ../../mesh.h:36
#5  0x00000055555998e8 in MeshBuilder::renderBuffer (this=0x5556a03ae0, indices=0x7ffffff2a0, iCount=18, vertices=0x7ffffff120, 
    vCount=12) at ../../mesh.h:1246
#6  0x00000055555c9868 in Inventory::renderTitleBG (this=0x5556a10810, sx=1, sy=1.125, alpha=255 '\377') at ../../inventory.h:1568
#7  0x00000055555c9d4c in Inventory::renderBackground (this=0x5556a10810) at ../../inventory.h:1626
#8  0x00000055555e486c in Level::renderInventoryEye (this=0x5556a10a90, eye=0) at ../../level.h:2855
#9  0x00000055555e49a8 in Level::renderInventory (this=0x5556a10a90) at ../../level.h:2876
#10 0x00000055555e4ba4 in Level::render (this=0x5556a10a90) at ../../level.h:2907
#11 0x00000055555e56bc in Game::frameRender () at ../../game.h:246
#12 0x00000055555e571c in Game::render () at ../../game.h:261
#13 0x00000055555e6a80 in main (argc=1, argv=0x7ffffff6a8) at main.cpp:427

```

So, the problem is on this call, on gapi_gl.h:

`glDiscardFramebufferEXT(GL_FRAMEBUFFER, count, discard);
`
It seems that glDiscardFramebufferEXT() is defined on some OSes here, on gapi_gl.h:

```
#if defined(_GAPI_GLES) && !defined(_OS_RPI) && !defined(_OS_CLOVER) && !defined(_OS_IOS)
    PFNGLDISCARDFRAMEBUFFEREXTPROC      glDiscardFramebufferEXT;
#endif

```

That's not right, so I added the _OS_XLESS_LINUX (KMSDRM is X-less, and uses GLES but not desktop GL):

```
#if defined(_GAPI_GLES) && !defined(_OS_RPI) && !defined(_OS_CLOVER) && !defined(_OS_IOS)  && !defined(_XLESS_LINUX)
    PFNGLDISCARDFRAMEBUFFEREXTPROC      glDiscardFramebufferEXT;
#endif
```

But now, I get this when building:
```

./../gapi_gl.h:1086:71: error: 'glDiscardFramebufferEXT' was not declared in this scope
                 glDiscardFramebufferEXT(GL_FRAMEBUFFER, count, discard);

```

It shouldn't happen, because glDiscardFramebufferEXT() is defined on my system's GLES and GLES2 includes, like this:

```
pi@raspberrypi:~/src/OpenLara/src/platform/kmsdrm$ grep glDiscardFramebufferEXT /usr/include/* -R
/usr/include/GLES/glext.h:GL_API void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments);
/usr/include/GLES2/gl2ext.h:GL_APICALL void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments);
/usr/include/SDL2/SDL_opengles2_gl2ext.h:GL_APICALL void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments);

```

...Or am I missing something?
Of course, on my local OpenLara sources, **GLES2/gl2ext.h is included**:

```
#elif defined(_OS_RPI) || defined(_OS_CLOVER) || defined(_OS_XLESS_LINUX)
    #include <GLES2/gl2.h>
    #include <GLES2/gl2ext.h>
    #include <EGL/egl.h>
    #include <EGL/eglext.h>

```

**Comment by XProger** [comment]
@vanfanel just comment glDiscardFramebufferEXT call

**Comment by vanfanel** [comment]
@XProger : Then I get these on execution:

```
pi@raspberrypi:~/tr$ gdb ./OpenLara 
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./OpenLara...done.
(gdb) r
Starting program: /home/pi/tr/OpenLara 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
EGL init succesfull
[New Thread 0x7fbe6d11b0 (LWP 683)]
! sound: write Broken pipe
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurredOpenLara (Nov 25 2018)

Vendor   : Broadcom
Renderer : VC4 V3D 2.1
Version  : OpenGL ES 2.0 Mesa 18.2.1
cache    : /home/pi/.OpenLara/
supports :
  variyngs count : 8
  binary shaders : true
  vertex arrays  : true
  depth texture  : true
  shadow sampler : false
  discard frame  : true
  NPOT textures  : true
  RG   textures  : false
  border color   : true
  anisotropic    : 0
  float textures : float = false, half = false

shader: cache warm-up...
shader: COMPOSE(0) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(4) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(2) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

! program: error: fragment shader uses too many input vectors (9 > 8)

shader: COMPOSE(2) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

! program: error: fragment shader uses too many input vectors (9 > 8)

shader: COMPOSE(2) u
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

! program: error: fragment shader uses too many input vectors (9 > 8)

shader: COMPOSE(2) ua
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

! program: error: fragment shader uses too many input vectors (9 > 8)

shader: COMPOSE(3) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(3) u
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(3) ua
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(3) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(0) u
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(0) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(0) ua
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(1) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: COMPOSE(1) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(2) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(2) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(2) u
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(2) ua
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(0) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(0) ua
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: AMBIENT(1) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: SHADOW(3) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: SHADOW(3) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: SHADOW(4) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: SHADOW(4) a
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: FILTER(0) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: FILTER(1) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: FILTER(2) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: FILTER(3) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: GUI(0) 
! shader: 0:1(12): warning: extension `GL_OES_standard_derivatives' unsupported in fragment shader

shader: cache is ready
meshes: 13
atlas: 1024 x 512
MegaMesh (i:57540 v:10975 a:4, size:466280)
Read Slots...

```

...and then after the intro video it segfaults again:

```
Thread 1 "OpenLara" received signal SIGSEGV, Segmentation fault.
0x0000007fbe9b5b64 in vbo_get_minmax_indices () from /usr/lib/dri/vc4_dri.so

```

**Comment by vanfanel** [comment]
@XProger : Any ideas on this? Could you setup an x-less test enviroment? A Pi with the VC4 driver will do :)

**Comment by pablomaiolo** [comment]
Hi, I was trying this out and I managed to debug it under desktop Linux. First I had to define GL_GLEXT_PROTOTYPES to work around the compile error on glDiscardFramebufferEXT and I also had to link libGL because that's where the function was defined (I found out by running objdump -T on libGL.so).

In order to be able to debug on desktop, switch to a virtual console and enable core dumps by running the command
`ulimit -c unlimited`
Then you need to run OpenLara in the same console and wait for it to crash. When it happens, you will lose signal to the display but you can switch to another virtual console and it will restore the framebuffer.
Now you have the core dump, so you can analyze it without needing to run the program again. Type
`gdb OpenLara core`
and you'll be able to check the backtrace, variables and so on.
In case you find it useful, I got this backtrace when it crashed (right after the intro FMV):
```
#0  vbo_get_minmax_index (prim=<optimized out>, count=<optimized out>, max_index=<synthetic pointer>, 
    min_index=<synthetic pointer>, ib=<optimized out>, ctx=<optimized out>) at ../src/mesa/vbo/vbo_minmax_index.c:307
#1  vbo_get_minmax_indices (ctx=ctx@entry=0x55aad0358b80, prims=prims@entry=0x7ffdb25fecf0, 
    ib=ib@entry=0x7ffdb25fecd0, min_index=min_index@entry=0x7ffdb25fec0c, max_index=max_index@entry=0x7ffdb25feca0, 
    nr_prims=nr_prims@entry=1) at ../src/mesa/vbo/vbo_minmax_index.c:377
#2  0x00007fa582cd8d1d in st_draw_vbo (ctx=0x55aad0358b80, prims=0x7ffdb25fecf0, nr_prims=1, ib=0x7ffdb25fecd0, 
    index_bounds_valid=<optimized out>, min_index=<optimized out>, max_index=<optimized out>, tfb_vertcount=0x0, 
    stream=0, indirect=0x0) at ../src/mesa/state_tracker/st_draw.c:166
#3  0x00007fa582d67db4 in _mesa_validated_drawrangeelements (baseInstance=0, numInstances=1, basevertex=0, 
    indices=0x198, type=5123, count=36, end=4294967295, start=0, index_bounds_valid=<optimized out>, mode=4, 
    ctx=0x55aad0358b80) at ../src/mesa/main/draw.c:850
#4  _mesa_validated_drawrangeelements (ctx=0x55aad0358b80, mode=4, index_bounds_valid=<optimized out>, start=0, 
    end=4294967295, count=36, type=5123, indices=0x198, basevertex=0, numInstances=1, baseInstance=0)
    at ../src/mesa/main/draw.c:782
#5  0x00007fa582d68ad3 in _mesa_exec_DrawElements (mode=4, count=36, type=5123, indices=0x198)
    at ../src/mesa/main/draw.c:1004
#6  0x000055aacf3a50ff in GAPI::DIP (mesh=0x55aad1697c28, range=...) at ../../gapi_gl.h:1184
#7  0x000055aacf3bdc8a in Core::DIP (mesh=0x55aad1697c28, range=...) at ../../core.h:998
#8  0x000055aacf3bddbb in Mesh::render (this=0x55aad1697c20, range=...) at ../../mesh.h:36
#9  0x000055aacf3c55e0 in MeshBuilder::renderModel (this=0x55aad15afad0, modelIndex=1, underwater=false)
    at ../../mesh.h:1393
#10 0x000055aacf3f167f in Inventory::Item::render (this=0x55aad1635c50, game=0x55aad15c2570, basis=...)
    at ../../inventory.h:516
#11 0x000055aacf3f5486 in Inventory::renderPage (this=0x55aad15e8d30, page=0) at ../../inventory.h:1463
#12 0x000055aacf3f700b in Inventory::render (this=0x55aad15e8d30, aspect=1.77777779) at ../../inventory.h:1720
#13 0x000055aacf412dcf in Level::renderInventoryEye (this=0x55aad15c2570, eye=0) at ../../level.h:2856
#14 0x000055aacf412ee6 in Level::renderInventory (this=0x55aad15c2570) at ../../level.h:2876
#15 0x000055aacf4130ae in Level::render (this=0x55aad15c2570) at ../../level.h:2907
#16 0x000055aacf41394a in Game::frameRender () at ../../game.h:246
#17 0x000055aacf41397f in Game::render () at ../../game.h:261
#18 0x000055aacf414b97 in main (argc=1, argv=0x7ffdb25ff7b8) at main.cpp:427
```

**Comment by XProger** [comment]
not actual

**Pull request closed without merging**
